.TH FINDCORE 1 "October 26, 2017"
.SH NAME
findcore \- find core dumps
.SH SYNOPSIS
.B findcore
.RI [ \-\-locate | DIRECTORY... ]
.SH DESCRIPTION
.B findcore
searches for core dumps (as identified by \fBfind\fR(1)) in the given directories.
If no directory is given, the working directory is searched.
If \fI\-\-locate\fR is given, \fBlocate(1)\fR is used instead of \fBfind(1)\fR.
.PP
The output is a list of core dump files, one per line.
.SH CAVEATS
\fBfind\fR(1) may occasionally mis-identify files, so you should check the
output before, for example, feeding it to \fBxargs rm\fR.
.SH "SEE ALSO"
.BR file (1),
.BR finddup (1).
.SH AUTHOR
Reuben Thomas <rrt@sc3d.org>.
