#!/bin/sh
# findcore
# Find core dumps (including from Valgrind)
# (c) Reuben Thomas <rrt@sc3d.org> 5/4/2006-26/10/2017
# This program is in the public domain

# Regular expression matching a core file
# N.B. Quoted for one level of expansion
# N.B. regex for find must match entire path; for locate, quicker if it doesn't
RE="/\\(vg\\)\\?core\\(\\.\\[0-9\\]\\+\\)\\?$"

( if [ $# -eq 0 ]; then
      locate --null --existing --regexp "$RE"
  else
      find "$@" -regextype posix-basic -regex ".*$RE" -type f -print0
  fi ) | \
    xargs -L 1 --null --no-run-if-empty sh -c 'if test "`file --brief --mime-type "$1"`" = "application/x-coredump" ; then echo "$1"; fi' list
