.TH ZUM 1 "October 26, 2017"
.SH NAME
zum \- free disk space by making holes in files
.SH SYNOPSIS
.B zum
[\fIFILE\fR]...
.SH DESCRIPTION
.B zum
attempts to make the given files sparse.
A sparse file replaces long series of NUL bytes by a count.
This works on most file systems, using \fBcp(1)\fR's \fB\-\-sparse\fR
option.
Note that since \fBzum\fR must make a copy of each file, some free space is
needed for it to work.
.PP
If no arguments are given, \fBzum\fR takes a list of files to process on
\fBstdin\fR, one per line.
.SH EXAMPLE
.IP
find . -type f -print0 | xargs -0 zum
.PP
.SH CAVEATS
If you use LILO as your bootloader, and run \fBzum\fR on your kernel image,
you must rerun lilo, or your system will be unbootable.
.PP
If \fBzum\fR runs out of disk space when processing files, just delete all
files that end with \fB__zum__\fR:
.IP
find DIRECTORY -name '*__zum__' -delete
.PP
After you free some space, it's safe to run it from the beginning again.
.SH SEE ALSO
.BR cp (1),
.BR finddup (1).
.SH AUTHOR
Oleg Kibirev <oleg@gd.cs.CSUFresno.edu>.
.PP
Manual page by Heiko Schlittermann <heiko@lotte.sax.de>.
